# Generated by Django 2.0.6 on 2018-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180612_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutperson',
            old_name='mail',
            new_name='first_name1',
        ),
        migrations.RenameField(
            model_name='aboutperson',
            old_name='name1',
            new_name='last_name1',
        ),
        migrations.RemoveField(
            model_name='aboutperson',
            name='name2',
        ),
        migrations.AddField(
            model_name='aboutperson',
            name='email',
            field=models.EmailField(db_index=True, default=True, max_length=254, unique=True),
        ),
    ]
