# Generated by Django 2.0.6 on 2018-06-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180612_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPerson',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default=True, max_length=96),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, default=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
