# Generated by Django 2.0.6 on 2018-06-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180612_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, default=True, max_length=254),
        ),
    ]
