# Generated by Django 2.0.6 on 2018-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20180614_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.IntegerField(choices=[('HOME', 'home'), ('BUSINESS', 'business')]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('HOME', 'home'), ('BUSINESS', 'business')], max_length=8),
        ),
    ]
