# Generated by Django 2.0.6 on 2018-06-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20180614_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='type',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='type',
        ),
    ]
