# Generated by Django 2.0.6 on 2018-06-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_address_email_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='mail',
        ),
    ]
