# Generated by Django 2.0.6 on 2018-06-15 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='emails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='contacts.Person'),
        ),
        migrations.AddField(
            model_name='phone',
            name='phones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='contacts.Person'),
        ),
    ]
