# Generated by Django 2.0.6 on 2018-06-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20180615_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='emails',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='phones',
            new_name='person',
        ),
    ]
